// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PasteleriaAPI.Data;

#nullable disable

namespace PasteleriaAPI.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260513030834_UpdatePastelCatalogos2")]
    partial class UpdatePastelCatalogos2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PasteleriaAPI.Entities.Catalogos.CatBizcocho", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("CatBizcochos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nombre = "Vainilla"
                        },
                        new
                        {
                            Id = 2,
                            Nombre = "Chocolate"
                        },
                        new
                        {
                            Id = 3,
                            Nombre = "Red Velvet"
                        },
                        new
                        {
                            Id = 4,
                            Nombre = "Zanahoria"
                        });
                });

            modelBuilder.Entity("PasteleriaAPI.Entities.Catalogos.CatCategoria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("categoria")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("CatCategorias");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            categoria = "Gourmet"
                        },
                        new
                        {
                            Id = 2,
                            categoria = "Infantil"
                        },
                        new
                        {
                            Id = 3,
                            categoria = "Boda"
                        },
                        new
                        {
                            Id = 4,
                            categoria = "Tradicional"
                        },
                        new
                        {
                            Id = 5,
                            categoria = "Dietético"
                        });
                });

            modelBuilder.Entity("PasteleriaAPI.Entities.Catalogos.CatGlaseado", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("CatGlaseados");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nombre = "Fondant"
                        },
                        new
                        {
                            Id = 2,
                            Nombre = "Crema de Mantequilla"
                        },
                        new
                        {
                            Id = 3,
                            Nombre = "Ganache de Chocolate"
                        },
                        new
                        {
                            Id = 4,
                            Nombre = "Queso Crema"
                        });
                });

            modelBuilder.Entity("PasteleriaAPI.Entities.Catalogos.CatRelleno", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("CatRellenos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nombre = "Fresa"
                        },
                        new
                        {
                            Id = 2,
                            Nombre = "Cajeta"
                        },
                        new
                        {
                            Id = 3,
                            Nombre = "Crema Pastelera"
                        },
                        new
                        {
                            Id = 4,
                            Nombre = "Nutella"
                        });
                });

            modelBuilder.Entity("PasteleriaAPI.Entities.Merma", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<int>("PastelId")
                        .HasColumnType("int");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PastelId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Mermas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Descripcion = "Pastel aplastado durante el transporte",
                            Fecha = new DateTime(2023, 10, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PastelId = 2,
                            UsuarioId = 2
                        },
                        new
                        {
                            Id = 2,
                            Descripcion = "Falta de decoración en el cheesecake",
                            Fecha = new DateTime(2023, 10, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PastelId = 5,
                            UsuarioId = 2
                        });
                });

            modelBuilder.Entity("PasteleriaAPI.Entities.Pastel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BizcochoId")
                        .HasColumnType("int");

                    b.Property<int>("CategoriaId")
                        .HasColumnType("int");

                    b.Property<string>("FotoUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("GlaseadoId")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RellenoId")
                        .HasColumnType("int");

                    b.Property<string>("Tamanio")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("BizcochoId");

                    b.HasIndex("CategoriaId");

                    b.HasIndex("GlaseadoId");

                    b.HasIndex("RellenoId");

                    b.ToTable("Pasteles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BizcochoId = 2,
                            CategoriaId = 1,
                            FotoUrl = "selva_negra.jpg",
                            GlaseadoId = 3,
                            Nombre = "Selva Negra",
                            RellenoId = 1,
                            Tamanio = "Grande"
                        },
                        new
                        {
                            Id = 2,
                            BizcochoId = 1,
                            CategoriaId = 2,
                            FotoUrl = "spiderman.jpg",
                            GlaseadoId = 1,
                            Nombre = "Pastel de Spiderman",
                            RellenoId = 2,
                            Tamanio = "Mediano"
                        },
                        new
                        {
                            Id = 3,
                            BizcochoId = 1,
                            CategoriaId = 4,
                            FotoUrl = "rosca.jpg",
                            GlaseadoId = 2,
                            Nombre = "Rosca de Reyes",
                            RellenoId = 3,
                            Tamanio = "Grande"
                        },
                        new
                        {
                            Id = 4,
                            BizcochoId = 3,
                            CategoriaId = 3,
                            FotoUrl = "boda.jpg",
                            GlaseadoId = 4,
                            Nombre = "Pastel Nupcial Blanco",
                            RellenoId = 4,
                            Tamanio = "Extra Grande"
                        },
                        new
                        {
                            Id = 5,
                            BizcochoId = 1,
                            CategoriaId = 5,
                            FotoUrl = "keto.jpg",
                            GlaseadoId = 4,
                            Nombre = "Cheesecake Keto",
                            RellenoId = 1,
                            Tamanio = "Chico"
                        },
                        new
                        {
                            Id = 6,
                            BizcochoId = 1,
                            CategoriaId = 4,
                            FotoUrl = "tres_leches.jpg",
                            GlaseadoId = 2,
                            Nombre = "Tres Leches",
                            RellenoId = 3,
                            Tamanio = "Mediano"
                        });
                });

            modelBuilder.Entity("PasteleriaAPI.Entities.Pedido", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Cantidad")
                        .HasColumnType("int");

                    b.Property<string>("Estatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<int>("PastelId")
                        .HasColumnType("int");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PastelId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Pedidos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Cantidad = 2,
                            Estatus = "Entregado",
                            Fecha = new DateTime(2023, 10, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PastelId = 1,
                            UsuarioId = 2
                        },
                        new
                        {
                            Id = 2,
                            Cantidad = 1,
                            Estatus = "En Proceso",
                            Fecha = new DateTime(2023, 10, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PastelId = 3,
                            UsuarioId = 2
                        },
                        new
                        {
                            Id = 3,
                            Cantidad = 5,
                            Estatus = "Pendiente",
                            Fecha = new DateTime(2023, 10, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PastelId = 6,
                            UsuarioId = 2
                        });
                });

            modelBuilder.Entity("PasteleriaAPI.Entities.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Rol")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Usuarios");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "admin@pasteleria.com",
                            Nombre = "Admin",
                            Password = "admin",
                            Rol = "Admin"
                        },
                        new
                        {
                            Id = 2,
                            Email = "cliente@correo.com",
                            Nombre = "Cliente",
                            Password = "123",
                            Rol = "Cliente"
                        });
                });

            modelBuilder.Entity("PasteleriaAPI.Entities.Merma", b =>
                {
                    b.HasOne("PasteleriaAPI.Entities.Pastel", "Pastel")
                        .WithMany()
                        .HasForeignKey("PastelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PasteleriaAPI.Entities.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pastel");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("PasteleriaAPI.Entities.Pastel", b =>
                {
                    b.HasOne("PasteleriaAPI.Entities.Catalogos.CatBizcocho", "Bizcocho")
                        .WithMany()
                        .HasForeignKey("BizcochoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PasteleriaAPI.Entities.Catalogos.CatCategoria", "Categoria")
                        .WithMany("Pasteles")
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PasteleriaAPI.Entities.Catalogos.CatGlaseado", "Glaseado")
                        .WithMany()
                        .HasForeignKey("GlaseadoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PasteleriaAPI.Entities.Catalogos.CatRelleno", "Relleno")
                        .WithMany()
                        .HasForeignKey("RellenoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Bizcocho");

                    b.Navigation("Categoria");

                    b.Navigation("Glaseado");

                    b.Navigation("Relleno");
                });

            modelBuilder.Entity("PasteleriaAPI.Entities.Pedido", b =>
                {
                    b.HasOne("PasteleriaAPI.Entities.Pastel", "Pastel")
                        .WithMany()
                        .HasForeignKey("PastelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PasteleriaAPI.Entities.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pastel");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("PasteleriaAPI.Entities.Catalogos.CatCategoria", b =>
                {
                    b.Navigation("Pasteles");
                });
#pragma warning restore 612, 618
        }
    }
}
