// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PasteleriaAPI.Data;

#nullable disable

namespace PasteleriaAPI.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260513015211_InitialPasteleria")]
    partial class InitialPasteleria
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PasteleriaAPI.Entities.Catalogos.CatCategoria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("categoria")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("CatCategorias");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            categoria = "Gourmet"
                        },
                        new
                        {
                            Id = 2,
                            categoria = "Infantil"
                        },
                        new
                        {
                            Id = 3,
                            categoria = "Boda"
                        },
                        new
                        {
                            Id = 4,
                            categoria = "Tradicional"
                        },
                        new
                        {
                            Id = 5,
                            categoria = "Dietético"
                        });
                });

            modelBuilder.Entity("PasteleriaAPI.Entities.Pastel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoriaId")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sabor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tamanio")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CategoriaId");

                    b.ToTable("Pasteles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoriaId = 1,
                            Nombre = "Selva Negra",
                            Sabor = "Chocolate y Cereza",
                            Tamanio = "Grande"
                        },
                        new
                        {
                            Id = 2,
                            CategoriaId = 2,
                            Nombre = "Pastel de Spiderman",
                            Sabor = "Vainilla",
                            Tamanio = "Mediano"
                        },
                        new
                        {
                            Id = 3,
                            CategoriaId = 4,
                            Nombre = "Rosca de Reyes",
                            Sabor = "Naranja",
                            Tamanio = "Grande"
                        },
                        new
                        {
                            Id = 4,
                            CategoriaId = 3,
                            Nombre = "Pastel Nupcial Blanco",
                            Sabor = "Red Velvet",
                            Tamanio = "Extra Grande"
                        },
                        new
                        {
                            Id = 5,
                            CategoriaId = 5,
                            Nombre = "Cheesecake Keto",
                            Sabor = "Fresa Sin Azúcar",
                            Tamanio = "Chico"
                        },
                        new
                        {
                            Id = 6,
                            CategoriaId = 4,
                            Nombre = "Tres Leches",
                            Sabor = "Vainilla Tradicional",
                            Tamanio = "Mediano"
                        });
                });

            modelBuilder.Entity("PasteleriaAPI.Entities.Pastel", b =>
                {
                    b.HasOne("PasteleriaAPI.Entities.Catalogos.CatCategoria", "Categoria")
                        .WithMany("Pasteles")
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Categoria");
                });

            modelBuilder.Entity("PasteleriaAPI.Entities.Catalogos.CatCategoria", b =>
                {
                    b.Navigation("Pasteles");
                });
#pragma warning restore 612, 618
        }
    }
}
