// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PasteleriaAPI.Data;

#nullable disable

namespace PasteleriaAPI.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260513032317_SeedMoreData3")]
    partial class SeedMoreData3
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PasteleriaAPI.Entities.Catalogos.CatBizcocho", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("CatBizcochos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nombre = "Vainilla"
                        },
                        new
                        {
                            Id = 2,
                            Nombre = "Chocolate"
                        },
                        new
                        {
                            Id = 3,
                            Nombre = "Red Velvet"
                        },
                        new
                        {
                            Id = 4,
                            Nombre = "Zanahoria"
                        },
                        new
                        {
                            Id = 5,
                            Nombre = "Mármol"
                        },
                        new
                        {
                            Id = 6,
                            Nombre = "Limón"
                        },
                        new
                        {
                            Id = 7,
                            Nombre = "Naranja"
                        },
                        new
                        {
                            Id = 8,
                            Nombre = "Esponja"
                        });
                });

            modelBuilder.Entity("PasteleriaAPI.Entities.Catalogos.CatCategoria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("categoria")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("CatCategorias");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            categoria = "Gourmet"
                        },
                        new
                        {
                            Id = 2,
                            categoria = "Infantil"
                        },
                        new
                        {
                            Id = 3,
                            categoria = "Boda"
                        },
                        new
                        {
                            Id = 4,
                            categoria = "Tradicional"
                        },
                        new
                        {
                            Id = 5,
                            categoria = "Dietético"
                        },
                        new
                        {
                            Id = 6,
                            categoria = "Quinceañera"
                        },
                        new
                        {
                            Id = 7,
                            categoria = "Temático"
                        },
                        new
                        {
                            Id = 8,
                            categoria = "Vegano"
                        },
                        new
                        {
                            Id = 9,
                            categoria = "Aniversario"
                        });
                });

            modelBuilder.Entity("PasteleriaAPI.Entities.Catalogos.CatGlaseado", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("CatGlaseados");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nombre = "Fondant"
                        },
                        new
                        {
                            Id = 2,
                            Nombre = "Crema de Mantequilla"
                        },
                        new
                        {
                            Id = 3,
                            Nombre = "Ganache de Chocolate"
                        },
                        new
                        {
                            Id = 4,
                            Nombre = "Queso Crema"
                        },
                        new
                        {
                            Id = 5,
                            Nombre = "Merengue Italiano"
                        },
                        new
                        {
                            Id = 6,
                            Nombre = "Espejo de Chocolate"
                        },
                        new
                        {
                            Id = 7,
                            Nombre = "Chantilly"
                        });
                });

            modelBuilder.Entity("PasteleriaAPI.Entities.Catalogos.CatRelleno", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("CatRellenos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nombre = "Fresa"
                        },
                        new
                        {
                            Id = 2,
                            Nombre = "Cajeta"
                        },
                        new
                        {
                            Id = 3,
                            Nombre = "Crema Pastelera"
                        },
                        new
                        {
                            Id = 4,
                            Nombre = "Nutella"
                        },
                        new
                        {
                            Id = 5,
                            Nombre = "Mermelada de Frambuesa"
                        },
                        new
                        {
                            Id = 6,
                            Nombre = "Crema de Limón"
                        },
                        new
                        {
                            Id = 7,
                            Nombre = "Durazno"
                        },
                        new
                        {
                            Id = 8,
                            Nombre = "Frutos Rojos"
                        });
                });

            modelBuilder.Entity("PasteleriaAPI.Entities.Merma", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<int>("PastelId")
                        .HasColumnType("int");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PastelId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Mermas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Descripcion = "Pastel aplastado durante el transporte",
                            Fecha = new DateTime(2023, 10, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PastelId = 2,
                            UsuarioId = 2
                        },
                        new
                        {
                            Id = 2,
                            Descripcion = "Falta de decoración en el cheesecake",
                            Fecha = new DateTime(2023, 10, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PastelId = 5,
                            UsuarioId = 2
                        },
                        new
                        {
                            Id = 103,
                            Descripcion = "El cliente reportó que el chocolate estaba muy amargo",
                            Fecha = new DateTime(2024, 2, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PastelId = 106,
                            UsuarioId = 2
                        },
                        new
                        {
                            Id = 104,
                            Descripcion = "Flores de fondant derretidas por el calor",
                            Fecha = new DateTime(2023, 11, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PastelId = 4,
                            UsuarioId = 2
                        },
                        new
                        {
                            Id = 105,
                            Descripcion = "La leche se derramó en la caja",
                            Fecha = new DateTime(2023, 10, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PastelId = 6,
                            UsuarioId = 2
                        });
                });

            modelBuilder.Entity("PasteleriaAPI.Entities.Pastel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BizcochoId")
                        .HasColumnType("int");

                    b.Property<int>("CategoriaId")
                        .HasColumnType("int");

                    b.Property<string>("FotoUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("GlaseadoId")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RellenoId")
                        .HasColumnType("int");

                    b.Property<string>("Tamanio")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("BizcochoId");

                    b.HasIndex("CategoriaId");

                    b.HasIndex("GlaseadoId");

                    b.HasIndex("RellenoId");

                    b.ToTable("Pasteles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BizcochoId = 2,
                            CategoriaId = 1,
                            FotoUrl = "https://images.unsplash.com/photo-1578985545062-69928b1d9587",
                            GlaseadoId = 3,
                            Nombre = "Selva Negra",
                            RellenoId = 1,
                            Tamanio = "Grande"
                        },
                        new
                        {
                            Id = 2,
                            BizcochoId = 1,
                            CategoriaId = 2,
                            FotoUrl = "https://images.unsplash.com/photo-1557925923-33b251dc32b0",
                            GlaseadoId = 1,
                            Nombre = "Pastel de Spiderman",
                            RellenoId = 2,
                            Tamanio = "Mediano"
                        },
                        new
                        {
                            Id = 3,
                            BizcochoId = 1,
                            CategoriaId = 4,
                            FotoUrl = "https://images.unsplash.com/photo-1535141192574-5d4897c12636",
                            GlaseadoId = 2,
                            Nombre = "Rosca de Reyes",
                            RellenoId = 3,
                            Tamanio = "Grande"
                        },
                        new
                        {
                            Id = 4,
                            BizcochoId = 3,
                            CategoriaId = 3,
                            FotoUrl = "https://images.unsplash.com/photo-1535254973040-607b474cb50d",
                            GlaseadoId = 4,
                            Nombre = "Pastel Nupcial Blanco",
                            RellenoId = 4,
                            Tamanio = "Extra Grande"
                        },
                        new
                        {
                            Id = 5,
                            BizcochoId = 1,
                            CategoriaId = 5,
                            FotoUrl = "https://images.unsplash.com/photo-1533134242443-d4fd215305ad",
                            GlaseadoId = 4,
                            Nombre = "Cheesecake Keto",
                            RellenoId = 1,
                            Tamanio = "Chico"
                        },
                        new
                        {
                            Id = 6,
                            BizcochoId = 8,
                            CategoriaId = 4,
                            FotoUrl = "https://images.unsplash.com/photo-1464349095431-e9a21285b5f3",
                            GlaseadoId = 7,
                            Nombre = "Tres Leches",
                            RellenoId = 3,
                            Tamanio = "Mediano"
                        },
                        new
                        {
                            Id = 101,
                            BizcochoId = 4,
                            CategoriaId = 8,
                            FotoUrl = "https://images.unsplash.com/photo-1606890737304-57a1ca8a5b62",
                            GlaseadoId = 4,
                            Nombre = "Pastel Vegano Zanahoria",
                            RellenoId = 4,
                            Tamanio = "Mediano"
                        },
                        new
                        {
                            Id = 102,
                            BizcochoId = 5,
                            CategoriaId = 9,
                            FotoUrl = "https://images.unsplash.com/photo-1562440499-64c9a111f713",
                            GlaseadoId = 1,
                            Nombre = "Especial 50 Años",
                            RellenoId = 2,
                            Tamanio = "Grande"
                        },
                        new
                        {
                            Id = 103,
                            BizcochoId = 2,
                            CategoriaId = 1,
                            FotoUrl = "https://images.unsplash.com/photo-1550617931-e17a7b70dce2",
                            GlaseadoId = 3,
                            Nombre = "Moka Intenso",
                            RellenoId = 4,
                            Tamanio = "Mediano"
                        },
                        new
                        {
                            Id = 104,
                            BizcochoId = 1,
                            CategoriaId = 2,
                            FotoUrl = "https://images.unsplash.com/photo-1616541823729-00fe0aacd32c",
                            GlaseadoId = 1,
                            Nombre = "Unicornio Mágico",
                            RellenoId = 1,
                            Tamanio = "Grande"
                        },
                        new
                        {
                            Id = 105,
                            BizcochoId = 6,
                            CategoriaId = 1,
                            FotoUrl = "https://images.unsplash.com/photo-1519869325930-281384150729",
                            GlaseadoId = 5,
                            Nombre = "Limón Cítrico",
                            RellenoId = 6,
                            Tamanio = "Chico"
                        },
                        new
                        {
                            Id = 106,
                            BizcochoId = 2,
                            CategoriaId = 1,
                            FotoUrl = "https://images.unsplash.com/photo-1606890737304-57a1ca8a5b62",
                            GlaseadoId = 3,
                            Nombre = "Chocolate Extremo",
                            RellenoId = 4,
                            Tamanio = "Extra Grande"
                        });
                });

            modelBuilder.Entity("PasteleriaAPI.Entities.Pedido", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Cantidad")
                        .HasColumnType("int");

                    b.Property<string>("Estatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<int>("PastelId")
                        .HasColumnType("int");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PastelId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Pedidos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Cantidad = 2,
                            Estatus = "Entregado",
                            Fecha = new DateTime(2023, 10, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PastelId = 1,
                            UsuarioId = 2
                        },
                        new
                        {
                            Id = 2,
                            Cantidad = 1,
                            Estatus = "En Proceso",
                            Fecha = new DateTime(2023, 10, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PastelId = 3,
                            UsuarioId = 2
                        },
                        new
                        {
                            Id = 3,
                            Cantidad = 5,
                            Estatus = "Pendiente",
                            Fecha = new DateTime(2023, 10, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PastelId = 6,
                            UsuarioId = 2
                        },
                        new
                        {
                            Id = 104,
                            Cantidad = 1,
                            Estatus = "Entregado",
                            Fecha = new DateTime(2023, 11, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PastelId = 4,
                            UsuarioId = 2
                        },
                        new
                        {
                            Id = 105,
                            Cantidad = 3,
                            Estatus = "Pendiente",
                            Fecha = new DateTime(2023, 11, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PastelId = 101,
                            UsuarioId = 2
                        },
                        new
                        {
                            Id = 106,
                            Cantidad = 1,
                            Estatus = "Cancelado",
                            Fecha = new DateTime(2023, 12, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PastelId = 2,
                            UsuarioId = 2
                        },
                        new
                        {
                            Id = 107,
                            Cantidad = 2,
                            Estatus = "Entregado",
                            Fecha = new DateTime(2023, 12, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PastelId = 104,
                            UsuarioId = 2
                        },
                        new
                        {
                            Id = 108,
                            Cantidad = 1,
                            Estatus = "En Proceso",
                            Fecha = new DateTime(2024, 1, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PastelId = 102,
                            UsuarioId = 2
                        },
                        new
                        {
                            Id = 109,
                            Cantidad = 4,
                            Estatus = "Pendiente",
                            Fecha = new DateTime(2024, 2, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PastelId = 106,
                            UsuarioId = 2
                        },
                        new
                        {
                            Id = 110,
                            Cantidad = 2,
                            Estatus = "Entregado",
                            Fecha = new DateTime(2024, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PastelId = 5,
                            UsuarioId = 2
                        });
                });

            modelBuilder.Entity("PasteleriaAPI.Entities.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Rol")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Usuarios");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "admin@pasteleria.com",
                            Nombre = "Admin Master",
                            Password = "admin",
                            Rol = "Admin"
                        },
                        new
                        {
                            Id = 2,
                            Email = "cliente@correo.com",
                            Nombre = "Cliente Juan",
                            Password = "123",
                            Rol = "Cliente"
                        });
                });

            modelBuilder.Entity("PasteleriaAPI.Entities.Merma", b =>
                {
                    b.HasOne("PasteleriaAPI.Entities.Pastel", "Pastel")
                        .WithMany()
                        .HasForeignKey("PastelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PasteleriaAPI.Entities.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pastel");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("PasteleriaAPI.Entities.Pastel", b =>
                {
                    b.HasOne("PasteleriaAPI.Entities.Catalogos.CatBizcocho", "Bizcocho")
                        .WithMany()
                        .HasForeignKey("BizcochoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PasteleriaAPI.Entities.Catalogos.CatCategoria", "Categoria")
                        .WithMany("Pasteles")
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PasteleriaAPI.Entities.Catalogos.CatGlaseado", "Glaseado")
                        .WithMany()
                        .HasForeignKey("GlaseadoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PasteleriaAPI.Entities.Catalogos.CatRelleno", "Relleno")
                        .WithMany()
                        .HasForeignKey("RellenoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Bizcocho");

                    b.Navigation("Categoria");

                    b.Navigation("Glaseado");

                    b.Navigation("Relleno");
                });

            modelBuilder.Entity("PasteleriaAPI.Entities.Pedido", b =>
                {
                    b.HasOne("PasteleriaAPI.Entities.Pastel", "Pastel")
                        .WithMany()
                        .HasForeignKey("PastelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PasteleriaAPI.Entities.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pastel");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("PasteleriaAPI.Entities.Catalogos.CatCategoria", b =>
                {
                    b.Navigation("Pasteles");
                });
#pragma warning restore 612, 618
        }
    }
}
